[project]
name = "template-repository"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pytest>=9.0.2", "pytest-cov>=7.0.0", "ruff>=0.14.14"]

[tool.ruff.lint]
select = [
    "F",   # Pyflakes
    "E",   # pycodestyle Error
    "W",   # pycodestyle Warning
    "I",   # isort
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "ANN", # flake8-annotations
    "ERA", # eradicate
    "PD",  # pandas-vet
    "PGH", # pygrep-hooks
    "PL",  # Pylint
    "RUF", # Ruff-specific rules
]

ignore = [
    "D203",   # incorrect-blank-line-before-clas
    "D213",   # multi-line-summary-second-line
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
]

[tool.pytest.ini_options]
testpaths = ["src"]
addopts = "--cov=src --cov-fail-under=90"
