name: CI

on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  python-style-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --cov --cov-fail-under=90 # Fail tests if coverage is below 90%
